var Schema = require('mongoose').Schema;
var passportLocalMongoose = require('passport-local-mongoose');
var db = require('./');

var User = new Schema({
  //'_id' used as userID for linking to other tables, autogenerated by DB
  //password registered from newusers table stored as salt and hash
    username: String,
    salt: String,
    hash: String, 
    email: String,
    HID: String, 
    firstLogin: Boolean,
    visPublic: Boolean,
    passReset: String,
    answered: Array
});
User.plugin(passportLocalMongoose, { usernameField: 'email' });

User.methods.resetPassword = function resetPassword(id, cb){
  //this.model('User').find({_id: id}, function(err, data){
   cb("data");
  //})
};

module.exports = db.model('user', User);
